// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhgxutirfgwqkbcjnlpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoZ3h1dGlyZmd3cWtiY2pubHB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTMzNzQsImV4cCI6MjA2NjAyOTM3NH0.39li901GKQ-tzqduFNrbbh__M5BX2a2Bw511A5OU8as";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);